### ISSUE TITLE
Installation fail on Mac OS X

### ISSUE THREAD

**Issue by amadanmath** [bkiefer/vonda#4]
[This line](https://github.com/bkiefer/vonda/blob/4da00f9c820c8076e7f4d61ad2d7444a0f892638/src/test/resources/miniproj/javcomp#L14) makes `mvn install` fail on OS X:

```
export CLASSPATH="${vondadir}/target/classes:`find "$vondadir"/repo/de/dfki/lt/hfc -name hfc\*.jar -printf '%h/%f:'`target/classes"
```

It depends on `-printf` option, which is a GNU extension to `find`. Since OS X does not come with GNU version of `find`, this breaks `mvn install`. Replacing the line with the following should be equivalent, and works with POSIX `find`:

```
export CLASSPATH="${vondadir}/target/classes:`find "$vondadir"/repo/de/dfki/lt/hfc -name hfc\*.jar -print | paste -s -d ":" -`:target/classes"
```

With this one change, `mvn install` succeeds on OS X (and should continue to work on GNU/Linux).

**Comment by amadanmath** [comment]
There is also the use of non-POSIX `readline -f` (in [`bin/vondac`](https://github.com/bkiefer/vonda/blob/c206497120da054c8a0375da9db701bebeb5b7fe/bin/vondac#L7) and in [`locallibs/cplan/cplanner`](https://github.com/bkiefer/cplan/blob/c487cfe271fd2722bffdefc03d669da8c037f905/cplanner#L4)), which prevents `./compile` from working. However, Mac OS X comes with Perl installed by default. Thus, it is possible to check if `readline -f` failed, and fallback to a Perl solution:

```
# bin/vondac
script_dir=`readlink -f "$0" 2> /dev/null` || script_dir=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`

# cplanner
APP_HOME=`readlink -f "$0" 2> /dev/null` || APP_HOME=`perl -MCwd -e 'print Cwd::abs_path shift' "$0"`
```

**Comment by bkiefer** [comment]
Thanks for hinting me to this problem, and providing the solutions. For the second, however, i prefered to use a shell-only solution i have just pushed. Could you possibly verify if it works for you, too? I've checked it on an older MacBook.

**Comment by amadanmath** [comment]
Confirmed to compile without issue.
